#!/bin/bash
cwd=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PATH=$cwd:$PATH

application_dir="/home/pi/.bcexchange/"
application_name="bcexchanged"
wallet02_unit="8"

wallet02_bak="$application_dir/wallet$wallet02_unit.dat.ramdisk.bak"
wallet02_bak2="$application_dir/wallet$wallet02_unit.dat.ramdisk.bak2"


if [ -f $wallet02_bak ]; then
        mv $wallet02_bak $wallet02_bak2
        $application_name -unit=$wallet02_unit backupwallet $wallet02_bak
else
        $application_name -unit=$wallet02_unit backupwallet $wallet02_bak

fi
